app:
  imageTag: latest
  url: sctracker-dev.aimingmed.local

idp:
  clientId: "--clientid--"
  clientSecret: "--clientsecret--"
  baseUrl: "--idpbaseurl--"
  tokenUrl: "--tokenurl--"
  disable: true

backendsctracker:
  image: ghcr.io/aimingmed/supplychain-tracker/backendsctracker
  replicas: 1
  port: 80
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  database:
    server: "database-sctracker"
    instance: "sctracker"
    database: "sctracker_dev"
    user: "postgres"
    password: "postgres"
    image: ghcr.io/aimingmed/supplychain-tracker/databasesctracker
  env:
    DATABASE_URL: "postgres://postgres:postgres@database-sctracker:5432/sctracker_dev"
    DATABASE_TEST_URL: "postgres://postgres:postgres@database-sctracker:5432/sctracker_test"
    SECRET_KEY: "your_secret_key_here"
    EXPIRE_TIME_MINUTES: "60"
    LOG_LEVEL: "DEBUG"