services:
  backend-sctracker:
    container_name: backend-sctracker
    image: backend-sctracker:v1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pipenv run uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
      - ../data/:/mnt/data
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@database:5432/sctracker_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@database:5432/sctracker_test
      - SECRET_KEY=your_secret_key_here
      - EXPIRE_TIME_MINUTES=60
    depends_on:
      - database-sctracker


  frontend-sctracker:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile.local
    container_name: frontend-sctracker
    image: frontend-sctracker:v1.0.0
    platform: linux/amd64
    volumes:
      - ./frontend-react:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3005:80"
    depends_on:
      - backend-sctracker
    environment:
      LOG_LEVEL: "DEBUG"
      VITE_REACT_APP_BASE_URL: "https://localhost/api/"


  database-sctracker:
    container_name: database-sctracker
    image: database-sctracker:v1.0.0
    build:
      context: ./database
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/sctracker_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@localhost:5432/sctracker_test
    volumes:
      - ./backend/migrations/:/mnt/migrations
      - ./database/postgres_data:/var/lib/postgresql/data

  nginx-sctracker:
    image: nginx:latest
    container_name: nginx-sctracker
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx_local.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend-sctracker
      # - frontend-sctracker
