services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pipenv run uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
      - ../data/:/mnt/data
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@database:5432/backend_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@database:5432/backend_test
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/backend_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@localhost:5432/backend_test
    volumes:
      - ./backend/migrations/:/mnt/migrations
      - ./database/postgres_data:/var/lib/postgresql/data
