[workspace]
authors = ["Sylens Wong <qium@aimingmed.com>"]
channels = ["conda-forge", "bioconda"]
name = "app"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
extra-index-urls = ["https://mirrors.shanghaitech.edu.cn/pypi/web/simple"]

[tasks]

[dependencies]
fastapi = "0.109.*"
uvicorn = "==0.26.0"
pydantic = "<2.7.0"
pydantic-settings = "==2.1.0"
asyncpg = "==0.29.0"
tortoise-orm = "==0.21.0"
gunicorn = "==21.0.1"
pandas = "==1.5.3"
numpy = "==1.26.4"
pytz = ">=2020.1"

openpyxl = "*"
requests = "*"
nicegui = ">=2.0"