apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: backend-sctracker
  labels:
    name: backend-sctracker
    app: sctracker
spec:
  replicas: { { .Values.backend-sctracker.replicas } }
  selector:
    matchLabels:
      name: backend-sctracker
      app: sctracker
  template:
    metadata:
      labels:
        name: backend-sctracker
        app: sctracker
    spec:
      containers:
        - name: backend-sctracker
          image: "{{.Values.backend-sctracker.image}}:{{.Values.app.imageTag}}"
          ports:
            - containerPort: { { .Values.backend-sctracker.port } }
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: { { .Values.backend-sctracker.resources.limits.cpu } }
              memory: { { .Values.backend-sctracker.resources.limits.memory } }
            requests:
              cpu: { { .Values.backend2.resources.requests.cpu } }
              memory: { { .Values.backend2.resources.requests.memory } }
          env:
            - name: LOG_LEVEL
              value: { { .Values.backend-sctracker.env.LOG_LEVEL } }
            - name: DISABLE_AUTH
              value: "{{.Values.idp.disable}}"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-sctracker
  labels:
    app: sctracker
    name: backend-sctracker
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: { { .Values.backend-sctracker.port } }
      port: { { .Values.backend-sctracker.port } }
      protocol: TCP
  selector:
    app: sctracker
    name: backend-sctracker
