
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-sctracker
  labels:
    app: sctracker
    name: database-sctracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sctracker
      name: database-sctracker
  template:
    metadata:
      labels:
        app: sctracker
        name: database-sctracker
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.backendsctracker.database.image | default \"postgres:15\" }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.backendsctracker.database.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.backendsctracker.database.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.backendsctracker.database.password }}"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: database-sctracker
  labels:
    app: sctracker
    name: database-sctracker
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: sctracker
    name: database-sctracker
