apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sctracker
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
spec:
  tls:
    - hosts:
        - {{.Values.app.url}}
      secretName: tls-secret
  rules:
    - host: {{.Values.app.url}}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: backendsctracker
                port:
                  number: {{.Values.backendsctracker.port}}
          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: backendsctracker
                port:
                  number: {{.Values.backendsctracker.port}}
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: backendsctracker
                port:
                  number: {{.Values.backendsctracker.port}}
          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: backendsctracker
                port:
                  number: {{.Values.backendsctracker.port}}